export const ENABLE_RANDOM_MODE = 'ENABLE_RANDOM_MODE';
export const QUERY_IMAGE_LIST = 'QUERY_IMAGE_LIST';
export const SELECT_BREED = 'SELECT_BREED';
export const SELECT_SUB_BREED = 'SELECT_SUB_BREED';
export const UPDATE_BREED_LIST = 'UPDATE_BREED_LIST';
export const UPDATE_SUB_BREED_LIST = 'UPDATE_SUB_BREED_LIST';
